const $=s=>document.querySelector(s);let state=null;
function name(p){return typeof p==="string"?p:(p?.name||"TBD")}
async function api(action,body){const r=await fetch("/api/index.js?action="+action,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body||{})});const d=await r.json();if(!r.ok)throw Error(d.error||"Request gagal");return d}
function bracket(s){const el=$("#adminBracket");if(!s.rounds?.length){el.innerHTML='<div class="empty">Bracket belum dimulai.</div>';return}el.innerHTML='<div class="bracket admin-bracket">'+s.rounds.map(r=>`<div class="round"><h3>${r.name}</h3><div class="matches">${r.matches.map(m=>`<div class="match ${m.status==="live"?"live":""}">${m.players.map(p=>{const n=name(p);return `<div class="slot ${m.winner&&name(m.winner)===n?"win":m.winner?"lose":""}" ${m.status==="live"&&n!=="TBD"?`data-mid="${m.id}" data-name="${encodeURIComponent(n)}"`:""}>${n}<span class="tag">${m.status==="live"?"KLIK UNTUK MENANGKAN":m.winner&&name(m.winner)===n?"WIN":""}</span></div>`}).join("")}</div>`).join("")}</div></div>`).join("")+(s.thirdPlace?`<div class="round"><h3>3RD PLACE</h3><div class="matches"><div class="match ${s.thirdPlace.status==="live"?"live":""}">${s.thirdPlace.players.map(p=>{const n=name(p);return `<div class="slot" ${s.thirdPlace.status==="live"&&n!=="TBD"?`data-mid="third" data-name="${encodeURIComponent(n)}"`:""}>${n}</div>`}).join("")}</div></div></div>`:"")+"</div>";el.querySelectorAll("[data-mid]").forEach(x=>x.onclick=()=>winner(x.dataset.mid,decodeURIComponent(x.dataset.name)))}
async function load(){try{const r=await fetch("/api/index.js?action=state",{cache:"no-store"});state=await r.json();if(state.admin){$("#loginBox").hidden=true;$("#panel").hidden=false;renderPlayers();bracket(state)}else{$("#loginBox").hidden=false;$("#panel").hidden=true}}catch(e){$("#loginMsg").textContent=e.message}}
function renderPlayers(){const p=state.players||[];$("#count").textContent=p.length+" PLAYER";$("#players").innerHTML=p.map((x,i)=>`<div class="player-row"><input data-n="${i}" class="pn" value="${esc(name(x))}"><input data-y="${i}" class="py" value="${esc(x?.youtube||"")}" placeholder="YouTube URL"><button data-save="${i}">SAVE</button></div>`).join("");document.querySelectorAll("[data-save]").forEach(b=>b.onclick=async()=>{const i=b.dataset.save;try{await api("update-player",{index:+i,name:$(`.pn[data-n="${i}"]`).value,youtube:$(`.py[data-y="${i}"]`).value});$("#adminMsg").textContent="Player tersimpan.";load()}catch(e){$("#adminMsg").textContent=e.message}})}
function esc(x){return String(x).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll('"',"&quot;")}
async function winner(mid,n){if(!confirm("Menangkan "+n+"?"))return;try{await api("winner",{matchId:mid,playerName:n});$("#adminMsg").textContent=n+" menang dan otomatis maju.";load()}catch(e){$("#adminMsg").textContent=e.message}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{await api("login",{username:$("#username").value,password:$("#password").value});load()}catch(x){$("#loginMsg").textContent=x.message}}
$("#addForm").onsubmit=async e=>{e.preventDefault();try{await api("add-player",{name:$("#playerName").value,youtube:$("#playerYoutube").value});$("#playerName").value="";$("#playerYoutube").value="";$("#adminMsg").textContent="Player ditambahkan.";load()}catch(x){$("#adminMsg").textContent=x.message}}
$("#startBtn").onclick=async()=>{if(!confirm("Mulai/randomize bracket sekarang?"))return;try{await api("start");$("#adminMsg").textContent="Bracket dimulai.";load()}catch(e){$("#adminMsg").textContent=e.message}}
$("#resetBtn").onclick=async()=>{if(!confirm("RESET SEMUA DATA TURNAMEN?"))return;try{await api("reset");$("#adminMsg").textContent="Tournament di-reset.";load()}catch(e){$("#adminMsg").textContent=e.message}}
$("#logoutBtn").onclick=async()=>{await api("logout");location.reload()}
load();setInterval(()=>{if(state)load()},1500);